config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'static_pages#home'

  get "/signin", to: "sessions#new"
  post "sessions/create", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  resources :users
  resources :recipes
  resources :ingredients
  resources :comments

  

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :user
belongs_to :recipe

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_amounts, dependent: :destroy
  has_many :recipes, through: :recipe_amounts, dependent: :destroy
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, through: :recipe_amounts, dependent: :destroy
  has_many :recipe_amounts, dependent: :destroy
  has_many :comments
  belongs_to :user
  mount_uploaders :pics, RecipePicUploader
  acts_as_taggable
  acts_as_taggable_on :chicken, :fish, :seafood, :meat, :others
  ratyrate_rateable "delizioso"
  validates_presence_of :title
end

app/models/recipe_amount.rb
class RecipeAmount < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/tag.rb
class Tag < ActiveRecord::Base
has_many :taggings
has_many :recipes, through: :taggings


end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
belongs_to :tag
belongs_to :recipe

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  has_many :ratings
  has_many :pics
  has_many :comments

  has_secure_password

  validates_presence_of :username, :name, :email
  validates_uniqueness_of :username, :email
  ratyrate_rateable "skills"
   ratyrate_rater
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  
  def new
  @comment = Comment.new
  end

  def create
  @comment = Comment.new(comment_params)
  @comment.user_id = current_user.id
  @comment.save 
  redirect_to recipe_path(@comment.recipe)
  end

  def edit 
  end

  private
  def comment_params
  params.require(:comment).permit(:id, :content, :recipe_id, :user_id)
  end



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]

  def index
    if params[:tag]
      @recipes = Recipe.tagged_with(params[:tag])
    else
      @recipes = Recipe.all
    end
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @comment = Comment.new
  end


  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.save
      flash[:success] = "You have successfully created your recipe."
      redirect_to recipe_path(@recipe)
    else
      flash[:danger] = "Your recipe was not created, please try again."
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "You have successfully updated your recipe"
      redirect_to recipe_path(@recipe)
    else
      flash[:danger] = "Please check the required fields and try again"
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

private

  def recipe_params
    params.require(:recipe).permit(:video_url, :title, :description, :tag_list, {pics: []})
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

# before_action :set_tag, only: [:show]

  def show
  end

  private

  # def set_tag
  #   @tag = Tag.find(params[:tag])
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Recipe Chef!"
      redirect_to @user
    else
      redirect_to new_user_path
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success]= "You have succesfully updated your user info"
      redirect_to @user
    else
      flash[:danger] = "Update failed, please check your parameters"
      render :edit
    end
  end

   def destroy
     @user.destroy
     redirect_to root_url
   end

  private

  def user_params
    params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipes/_form.html.erb
<%=  form_for(@recipe) do |f| %>

<div class="field">
  <%= f.label :pics, "Upload pics!"%><br />
  <%= f.file_field :pics, multiple: true %>
</div>

 <div class= "field"> <%= f.label :video_url, "Video" %> <br>
  <%= f.url_field :video_url %> </div>

   <div class="field"> <%= f.label :title, "Title"  %><br>
  <%= f.text_field  :title %></div>


 <div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
</div>

<div class="field">
  <%= f.label :description, "Ingredients" %><br>
  <%= f.text_area :description %>
</div>

<div class="field"><%= f.label :time, "Duration" %> <br>
<%= f.text_field :time %></div>

  <div class='action'>
  <%= f.submit %>
  </div>
  <% end %>

app/views/recipes/edit.html.erb
<h1> Edit Recipe </h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<div class="row">
<div class="text-center">

<h1> <img src="https://s-media-cache-ak0.pinimg.com/236x/70/09/19/7009193184270fbdef1d81ee0a55a3ba.jpg" height="200" width="200"></h1>

</div>
</div>
<br><br>
<div class="row" id="recipe-list">
<% @recipes.sort_by{|recipe| recipe.created_at}.reverse.each do |recipe| %>
  <div class="col-md-4" align="center" id="individual-recipe">
<font size="6"> <%= link_to recipe.title, recipe %><br></font>
<a href="<%= recipe_path(recipe)%>"> <iframe src="<%= recipe.video_url%>" width="350" height="250" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>
<br>
<%= recipe.time %>
<%= rating_for recipe, "delizioso" %>
<br>
</div>
<% end %>
</div>

app/views/recipes/new.html.erb
<h1><img src="http://photos.gograph.com/thumbs/CSP/CSP274/k19651351.jpg" width="175" height="175"></h1>

<%= render 'form' %>

app/views/recipes/search.html.erb
<div class="row">
<div class="text-center">
<h1>Search Results for "<%= @search_term %>"</h1>
</div>
</div>
<br><br>
<div class="row">
<% @recipes.each do |recipe| %>
  <div class="col-md-4" align="center">
  <font size="6"> <%= link_to recipe.title, recipe %><br></font>
  <a href="<%= recipe_path(recipe)%>">
  <iframe src="<%=recipe.video_url%>" width="350" height="250"
    style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"
      allowFullScreen="true"></iframe><br>
<br>
</div>
<% end %>
</div>

app/views/recipes/show.html.erb
<div class="col-md-9 content">
  <div class="page" align="center">
<iframe src="<%= @recipe.video_url%>" width="560" height="315" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>

<div class"description" align="center">
<h2><u>Dish Name</u></h2>
<font size="5"><%= @recipe.title %></font><br>
<h2><u>Ingredients</u></h2>
<font size="3"><u><%= @recipe.description %></u></font> 
<h2><u>Cooking Time</u></h2>
<font size="2"> <%= @recipe.time %><br></font>
</div>
</div> <!-- end row -->
</div><!-- end page-header -->
<br><br>

<div class="row" align="center">
<div class="col-md-9" align="center">
<% if current_user %>
<font size="5"><b><u>Delizioso : <%= rating_for_user @recipe, current_user, "delizioso",  disable_after_rate: false %></b></u></font>
</div>
</div>

<div class="row" align="right">
<div class="col-md-9" align="center">
<h2><u> Reviews </u></h2>
<% @recipe.comments.each do |comment| %>
<b><%= comment.user.name%> says:<br></b>
<%= comment.content%><br>
<% end %><br>
<div class="col-md-4">
<div style="position: absolute; left: 100%; margin-center: 25px; width: 325px;">
<%=form_for  @comment do |f|%>
  <%= f.label :content, "Comments"%>:
  <%= f.text_area :content, class: "form-control", data: {textarea: "comment"}%>
  <%= f.hidden_field :recipe_id, value: @recipe.id %>
  <%= f.submit "Submit", class: "btn btn-primary", data: {send: "comment"}%> 
</div>
</div>
<%end%>
</div>
<%end%> 
</div>
</div>

app/views/tags/show.html.erb
<div class="row">
<div class="text-center">
<h1><%= @tag.name %></h1>
</div>
</div>
<br><br>
<div class="row">
<% @tag.recipes.each do |recipe| %>
  <div class="col-md-4" align="center">
<a href="<%= recipe_path(recipe)%>"> <img src="<%=recipe.video_url%>" height="250", width="250"><br>
<%= link_to recipe.title, recipe %><br>
<p> Tags: <%= raw recipe.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
<br>
</div>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>


 <% if @user.errors.any? %>
   <div id="error_explanation">
    <div class="alert alert-danger fade-in">
     <h3>
       Please correct the following errors:
     </h3>
     <ul>
     <% @user.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

<br>
<br>
<br>

<div>
      <%= f.label :name %> <br>
      <%= f.text_field :name %> <br>
    </div>
    <div>
      <%= f.label :username %> <br>
      <%= f.text_field :username %> <br>
    </div>
    <div>
      <%= f.label :email %> <br>
      <%= f.text_field :email %> <br>
    </div>
    <div>
      <%= f.label :password %> <br>
      <%= f.password_field :password %> <br>
    </div>
    <div>
      <%= f.label :password_confirmation %> <br>
      <%= f.password_field :password_confirmation %> <br>
    </div>
    
  <br>
  <br>
  <%= f.submit "Submit" %>
<% end %>
</div>
<br>

app/views/users/create.js.erb
$('#notification').append("Congratulations, you're registered!")

app/views/users/edit.html.erb
<h1> <img src="http://www.public-domain-photos.com/free-cliparts-4/computer/actions/edit_user.png" height="175" width="175"> </h1>

<%= render 'form' %><br>

app/views/users/index.html.erb
<div class="row">
<div class="text-center">
<h1><img src="http://previews.123rf.com/images/miceking/miceking1506/miceking150600554/40809510-Chef-word-illustration--Stock-Vector.jpg" height="150" width="150"></h1>
</div>
</div>
<br><br>
<div class="row">
<% @users.all.each do |user| %>
  <div class="col-md-4" align="center">
<a href="<%= user_path(user)%>"> <img src="<%=user.image_url%>" height="250", width="250"><br>
<%= link_to user.name, user_path(user) %><br>
<%= rating_for user, "skills" %>
<br>
</div>
<% end %>
</div>

app/views/users/new.html.erb
<div id="form">

<%= render 'form' %>

Already have an account? <%= link_to "Click here.", root_path %>

<div id="notification">

app/views/users/show.html.erb
<div class="col-md-9 content">
  <div class="page">
    <article>
      <div class="page-header page-header-resume">
       <h2><%= @user.username%></h2>
        <img src="<%= @user.image_url%>" alt="" title="" />
         <div class="row" align="center">
         <br>
         <% if current_user %>
        <%= link_to "Create a recipe", new_recipe_path, class: "btn btn-primary" %>
        <% end %>
     </div> <!-- end row -->
      </div><!-- end page-header -->

<div class="row" align ="center">
  <h3> Chef Rating : <%= rating_for @user, "skills",  disable_after_rate: false %>
</h3>
  <div class="row">
    <% if @user.recipes %>
    <h1></h1>
      <div class="page-header page-header-resume">
     
    
  </div>
   <h2>Recipes</h2>
</div>
  <% @user.recipes.each do |recipe| %>

    <div class="col-md-4" align="left">
  <%= link_to recipe.title, recipe_path(recipe) %> <%= rating_for recipe, "delizioso" %>
  <br>
  <p> Tags: <%= raw recipe.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
  <br>

</div><!-- end col-md-4 -->
  <% end %>
  <% end %>  
</div><!-- end row -->
<div class="row" align="center">
<% if current_user %>
<%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-warning"%>
<% end %>
</div>
</div>
</article><!-- end article -->
</div><!-- end page -->
</div><!-- end col-mid-9 -->