config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'static_pages#home'

  get "/signin", to: "sessions#new"
  post "sessions/create", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  resources :users
  resources :recipes
  resources :ingredients
  resources :comments

  

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :user
belongs_to :recipe

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_amounts, dependent: :destroy
  has_many :recipes, through: :recipe_amounts, dependent: :destroy
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, through: :recipe_amounts, dependent: :destroy
  has_many :recipe_amounts, dependent: :destroy
  has_many :comments
  belongs_to :user
  mount_uploaders :pics, RecipePicUploader
  acts_as_taggable
  acts_as_taggable_on :chicken, :fish, :seafood, :meat, :others
  ratyrate_rateable "delizioso"
  validates_presence_of :title
end

app/models/recipe_amount.rb
class RecipeAmount < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/tag.rb
class Tag < ActiveRecord::Base
has_many :taggings
has_many :recipes, through: :taggings


end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
belongs_to :tag
belongs_to :recipe

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  has_many :ratings
  has_many :pics
  has_many :comments

  has_secure_password

  validates_presence_of :username, :name, :email
  validates_uniqueness_of :username, :email
  ratyrate_rateable "skills"
   ratyrate_rater
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

# before_action :set_tag, only: [:show]

  def show
  end

  private

  # def set_tag
  #   @tag = Tag.find(params[:tag])
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class= "col-mid-8">
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"> <%= message %>
    <a class="close" data-dismmiss="alert"> &#215; </a>
    </div>
    <% end %>
  </div>
  </div>

app/views/layouts/_navbar.html.erb
   <div class="wrapper">
      <div class="row">
        <div class="col-md-3 sidebar">
          <div class="navbar" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#rebound-navbar-collapse"><span class="fa fa-bars"></span> Menu</button>
              <p class="navbar-brand"> Recipe Chefs </p>
              <br>
             <font face="verdana"> <p class="brand-text">Hmmmmm</p>
            </div><!-- end navbar-header -->
            <div class="collapse navbar-collapse" id="rebound-navbar-collapse">
              <ul class="nav navbar-nav">
             
                <li class="title">Menu</li>
                <li> <%= link_to "Home", root_url %></li>
                <% if current_user %>
                <li> <%=link_to "Profile", user_path(current_user) %>
                <% end %>
                <li> <%= link_to "Chefs", users_path%></li>
                 <li> <%= link_to "Recipes", recipes_path%></li>
                 <% if current_user %>
                  <li><%= link_to "Log Out", signout_path, method: :delete %></li>
                  <% end %>
              </ul>
              <form class="navbar-form" role="search" action="/search" method="post">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search" name="q" value="" />
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" id="search-submit"><span class="fa fa-search"></span></button>
                  </span>
                </div><!-- end input group -->
              </form><!-- end navbar-form -->
              <ul class="nav navbar-nav filter-portfolio">

                <li class="title">Tags</li>
            
              </ul>
              <ul class="nav navbar-nav nav-social hidden-sm hidden-xs">
                <li class="title">Social</li>
                <li><a href="https://twitter.com/bourdain?lang=en">Twitter</a></li>
                <li><a href="https://www.facebook.com/buzzfeedtasty/?fref=ts">Facebook</a></li>
                <li><a href="https://www.linkedin.com/company/chefsbest">LinkedIn</a></li>
              </ul>
            </div><!-- end navbar-collapse -->
          </div><!-- end navbar -->
        </div><!-- end col -->
           <div class="row">
          <div class="col-md-8">
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeChef</title>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <title>Rebound - Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Rebound - Responsive Portfolio Theme for Twitter Bootstrap. Responsive HTML5, CSS3 and jQuery.">
    <meta name="author" content="Pukeko Design Studio">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/sample/logo-144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/sample/logo-114.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/sample/logo-72.png">
                    <link rel="apple-touch-icon-precomposed" href="img/sample/logo-57.png">
                                   <link rel="shortcut icon" href="img/sample/logo.png">
</head>
<body background="foodcolours.jpg">
<%= render "layouts/navbar" %>
<%= render "layouts/messages" %>
<%= yield %>
</div>

</body>
</html>